/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChorusEffect: typeof import('./src/components/synth-effects/ChorusEffect.vue')['default']
    ConvolverEffect: typeof import('./src/components/synth-effects/ConvolverEffect.vue')['default']
    DelayEffect: typeof import('./src/components/synth-effects/DelayEffect.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    GeneralSettings: typeof import('./src/components/settings/GeneralSettings.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    KeybindsSettings: typeof import('./src/components/settings/KeybindsSettings.vue')['default']
    MidiChannelButton: typeof import('./src/components/MidiChannelButton.vue')['default']
    MidiParamDialog: typeof import('./src/components/MidiParamDialog.vue')['default']
    OverdriveEffect: typeof import('./src/components/synth-effects/OverdriveEffect.vue')['default']
    PhaserEffect: typeof import('./src/components/synth-effects/PhaserEffect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./src/components/settings/SettingsDialog.vue')['default']
    SynthDialog: typeof import('./src/components/synth/SynthDialog.vue')['default']
    SynthEffects: typeof import('./src/components/synth/SynthEffects.vue')['default']
    SynthList: typeof import('./src/components/synth/SynthList.vue')['default']
    SynthMidiSettings: typeof import('./src/components/synth/SynthMidiSettings.vue')['default']
    SynthPiano: typeof import('./src/components/synth/SynthPiano.vue')['default']
    SynthSettings: typeof import('./src/components/synth/SynthSettings.vue')['default']
    SynthWaveformSettings: typeof import('./src/components/synth/SynthWaveformSettings.vue')['default']
    WavetableGraph: typeof import('./src/components/WavetableGraph.vue')['default']
  }
}
